name: Deploy to EC2 on push

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "~/intro_project"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/intro_project
            if [ ! -d "backend_env" ]; then
              python3 -m venv backend_env
            fi
            source backend_env/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pkill -f runserver || true
            nohup python manage.py runserver 0.0.0.0:8000 > output.log 2>&1 & disown
